### ISSUE TITLE
Audio Uploading Error

### ISSUE THREAD

**Issue by peylight** [FayasNoushad/YouTube-Downloader#6]
When i try to upload audio:
```
Jun 18 03:04:11 debian_10 bash[24829]: Pyrogram v1.2.9, Copyright (C) 2017-2021 Dan <https://github.com/delivrance>
Jun 18 03:04:11 debian_10 bash[24829]: Licensed under the terms of the GNU Lesser General Public License v3 or later (LGPLv3+)
Jun 18 03:04:11 debian_10 bash[24829]: [warn] Skip parser 'MpegAudioFile': Unable to create frame #0
Jun 18 03:04:12 debian_10 bash[24829]: [warn] Skip parser 'MpegAudioFile': Unable to create frame #0
Jun 18 03:04:12 debian_10 bash[24829]: [warn] Skip parser 'JpegFile': Invalid file signature
Jun 18 03:04:12 debian_10 bash[24829]: 2021-06-18 03:04:12,314 - pyrogram.dispatcher - ERROR - 'NoneType' object has no attribute 'has'
Jun 18 03:04:12 debian_10 bash[24829]: Traceback (most recent call last):
Jun 18 03:04:12 debian_10 bash[24829]:   File "/root/youtube-dl2/venv/lib/python3.7/site-packages/pyrogram/dispatcher.py", line 217, in handler_worker
Jun 18 03:04:12 debian_10 bash[24829]:     await handler.callback(self.client, *args)
Jun 18 03:04:12 debian_10 bash[24829]:   File "/home/telegram-bot/YouTube-Downloader/plugins/cb_buttons.py", line 22, in button
Jun 18 03:04:12 debian_10 bash[24829]:     await youtube_dl_call_back(bot, update)
Jun 18 03:04:12 debian_10 bash[24829]:   File "/home/telegram-bot/YouTube-Downloader/plugins/youtube_dl_button.py", line 221, in youtube_dl_call_back
Jun 18 03:04:12 debian_10 bash[24829]:     if metadata.has("width"):
Jun 18 03:04:12 debian_10 bash[24829]: AttributeError: 'NoneType' object has no attribute 'has'

```

**Comment by FayasNoushad** [comment]
First send thumbnail and try
